stages:
  data_ingestion:
    cmd: python src/mlProject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlProject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python src/mlProject/pipeline/stage_02_data_validation.py
    deps:
      - src/mlProject/pipeline/stage_02_data_validation.py
      - config/config.yaml
    outs:
      - artifacts/data_validation


  model_trainer:
    cmd: python src/mlProject/pipeline/stage_04_model_trainer.py
    deps:
      - src/mlProject/pipeline/stage_04_model_trainer.py
      - config/config.yaml
    outs:
      - artifacts/model_trainer
  

  model_evaluation:
    cmd: python src/mlProject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mlProject/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
   
  